---
name: ci
permissions:
  contents: read
  packages: write
on:
  push:
    branches:
      - dev
      - main
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push sha
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: ./Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/architec-ton/wallet-tma:${{ github.sha }}

      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: ./Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/architec-ton/wallet-tma:latest
